-- Seed Data for Engineering Club Website (No Mock Users)

-- 1. Insert Club Settings
insert into club_settings (id, club_name, allowed_email_domain, budget_ceiling_cents)
values ('default', 'Fairview High School Engineering Club', 'bvsd.org', 5000000)
on conflict (id) do nothing;

-- 2. Competitions
-- impact_level: world > national > regional > local (drives directory filter)
insert into competitions (id, slug, name, description, organizer, status, impact_level, season, registration_opens_at, registration_closes_at, event_starts_at, event_ends_at, max_teams, max_team_size, entry_fee_cents, external_url, created_by)
values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'first-robotics-2027', 'FIRST Robotics Competition — BIOCORE 2027', 'The premier international high school robotics challenge. Teams design, CNC-machine, wire, and program industrial-grade 125-lb robots in an intensive build cycle after the January 9, 2027 game reveal. The 2027 BIOCORE season (presented by Haas) explores what sustains life on Earth, culminating at the FIRST Championship in Houston, April 28 – May 1, 2027.', 'FIRST (For Inspiration & Recognition of Science & Technology)', 'active', 'world', '2026-27', now() - interval '30 days', now() + interval '30 days', now() + interval '90 days', now() + interval '94 days', 2, 35, 600000, 'https://www.firstinspires.org/robotics/frc', null),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'nasa-rover-challenge', 'NASA Human Exploration Rover Challenge 2027', 'Design, fabricate, and pilot a human-powered collapsible rover capable of traversing a rugged half-mile simulated lunar and Martian obstacle course at the U.S. Space & Rocket Center in Huntsville, AL (April 21–24, 2027). Teams complete real-time core sampling and equipment deployment while meeting strict telemetry and safety standards.', 'NASA Marshall Space Flight Center', 'active', 'world', '2026-27', now() - interval '20 days', now() + interval '15 days', now() + interval '120 days', now() + interval '124 days', 2, 8, 0, 'https://www.nasa.gov/roverchallenge', null),
  ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'american-rocketry-2027', 'American Rocketry Challenge 2027', 'The world''s largest student rocket contest. Teams engineer and launch model rockets carrying two raw Grade A eggs to exactly 800 feet with a flight duration of 37–40 seconds, returning the payload intact. Registration for the 2027 cycle closes December 6, 2026 ($195/team); National Finals follow in spring 2027.', 'Aerospace Industries Association & NAR', 'planned', 'national', '2026-27', now() + interval '10 days', now() + interval '60 days', now() + interval '180 days', now() + interval '182 days', 3, 10, 19500, 'https://www.rocketrychallenge.org', null),
  ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'solar-car-challenge', 'Solar Car Challenge 2027', 'High school teams design, build, and race full-scale roadworthy solar-electric vehicles. Squads engineer custom roll cages, MPPT solar charging arrays, lithium battery management systems (BMS), and composite aerodynamic fairings. The 2027 cycle returns to the closed-track event at Texas Motor Speedway (July 18–21, 2027); official registration closes March 1.', 'Solar Car Challenge Foundation', 'planned', 'national', '2026-27', now() + interval '20 days', now() + interval '165 days', now() + interval '305 days', now() + interval '308 days', 1, 15, 80000, 'https://www.solarcarchallenge.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'ftc-biobuzz-2026-27', 'FIRST Tech Challenge — BIOBUZZ 2026-27', 'Head-to-head robotics for smaller teams with a lighter footprint than FRC. The 2026-27 BIOBUZZ season (presented by RTX) kicked off September 12, 2026, challenging teams to design, build, and program robots around a pollination-inspired field game, with judged awards and an engineering portfolio.', 'FIRST (For Inspiration & Recognition of Science & Technology)', 'active', 'world', '2026-27', now() - interval '45 days', now() + interval '45 days', now() + interval '150 days', now() + interval '152 days', 2, 15, 29500, 'https://www.firstinspires.org/robotics/ftc', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeef', 'vex-override-2026-27', 'VEX V5 Robotics Competition — Override', 'The 2026-27 VEX V5RC game "Override" challenges middle and high school teams to design, build, and program competitive robots from the V5 ecosystem. Local qualifiers run November 2026 – February 2027, the US OPEN lands in March, and the World Championship follows in April 2027.', 'Robotics Education & Competition (REC) Foundation', 'active', 'world', '2026-27', now() - interval '40 days', now() + interval '40 days', now() + interval '130 days', now() + interval '132 days', 2, 10, 20000, 'https://www.vexrobotics.com/competition', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1', 'zero-robotics-2026-27', 'MIT Zero Robotics High School Tournament', 'Program NASA SPHERES/Astrobee satellites aboard the International Space Station. Teams write strategy code in C/C++ through online simulation rounds; the season culminates in a live championship aboard the ISS streamed from MIT, judged by astronauts. Registration runs through the fall each year.', 'MIT & NASA', 'active', 'world', '2026-27', now() - interval '25 days', now() + interval '25 days', now() + interval '140 days', now() + interval '141 days', 1, 20, 0, 'https://zerorobotics.mit.edu', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2', 'seaperch-international-2027', 'SeaPerch International Challenge 2027', 'Build and pilot a Remotely Operated underwater Vehicle (ROV) from a standard kit, then compete in in-pool mission courses and technical design reports. Regional qualifiers feed the international championship each spring. A low-cost entry point into marine & ocean engineering.', 'RoboNation / Office of Naval Research', 'active', 'world', '2026-27', now() - interval '15 days', now() + interval '90 days', now() + interval '200 days', now() + interval '202 days', 2, 6, 12500, 'https://seaperch.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3', 'nasa-student-launch-2027', 'NASA Student Launch 2027', 'A nine-month, research-based rocketry challenge mirroring the NASA engineering lifecycle. Teams propose, design, build, and fly high-powered rockets carrying a science payload, passing multiple formal design reviews before Launch Day in Huntsville, AL (April 2027). Application required in the fall.', 'NASA Marshall Space Flight Center', 'active', 'national', '2026-27', now() - interval '10 days', now() + interval '20 days', now() + interval '210 days', now() + interval '213 days', 1, 12, 0, 'https://www.nasa.gov/learning-resources/nasa-student-launch/', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4', 'cyberpatriot-xviii-2026-27', 'CyberPatriot National Youth Cyber Defense Competition', 'The nation''s largest cybersecurity competition, run by the Air & Space Forces Association. Teams act as newly hired IT professionals hardening virtual networks (Windows, Linux, Cisco) against simulated attacks across online rounds, with the top teams advancing to the National Finals in the Washington, D.C. area.', 'Air & Space Forces Association (AFA)', 'active', 'national', '2026-27', now() - interval '35 days', now() + interval '10 days', now() + interval '60 days', now() + interval '61 days', 2, 6, 20500, 'https://www.uscyberpatriot.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5', 'tsa-teams-2027', 'TSA TEAMS — Tests of Engineering Aptitude, Math & Science', 'Teams of 4–6 students collaborate on real-world engineering scenarios: a 90-minute multiple-choice exam plus an essay-style design-build portion. State-level competitions feed the national round at the TSA National Conference. Ideal for strong math/science students who want a low-time-commitment competition.', 'Technology Student Association (TSA)', 'planned', 'national', '2026-27', now() + interval '30 days', now() + interval '120 days', now() + interval '150 days', now() + interval '151 days', 2, 6, 12500, 'https://tsaweb.org/teams', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6', 'samsung-solve-2026-27', 'Samsung Solve for Tomorrow 2026-27', 'Use STEM to tackle a real problem in your community. Public-school teams submit project ideas, then develop prototypes with Samsung technology; national winners earn $100,000 prize packages. Runs entirely through the school year with an educator-led application each fall.', 'Samsung Electronics America', 'active', 'national', '2026-27', now() - interval '30 days', now() + interval '60 days', now() + interval '180 days', now() + interval '181 days', 1, 10, 0, 'https://www.samsung.com/us/solvefortomorrow/', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7', 'co-science-bowl-2027', 'Colorado Regional Science Bowl 2027', 'Fast-paced buzzer-style competition covering biology, chemistry, physics, math, and energy technology, hosted by the Department of Energy. Regional winners earn an all-expenses-paid trip to the National Science Bowl in Washington, D.C. Great fit for quiz-bowl-minded engineers.', 'U.S. Department of Energy', 'planned', 'regional', '2026-27', now() + interval '15 days', now() + interval '100 days', now() + interval '140 days', now() + interval '141 days', 2, 5, 0, 'https://science.osti.gov/wdts/nsb', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee8', 'fhs-maker-sprint-fall-2026', 'FHS Maker Sprint — Fall 2026', 'Our own intra-club design sprint: small teams get a surprise kit of materials and 48 hours to prototype a solution to a secret design brief, judged by local industry mentors. Low stakes, high fun — the best on-ramp for first-year members before committing to a national season.', 'FHS Engineering Club', 'planned', 'local', '2026-27', now() - interval '5 days', now() + interval '12 days', now() + interval '30 days', now() + interval '32 days', 8, 4, 500, null, null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9', 'denver-metro-engineering-expo-2027', 'Denver Metro Engineering Expo 2027', 'A regional showcase where Colorado high school engineering teams present projects to judges from local universities and industry — mechanical, aerospace, and civil design tracks with feedback sessions. Strong practice ground for portfolio presentations before national events.', 'Denver Metro STEM Coalition', 'planned', 'regional', '2026-27', now() + interval '45 days', now() + interval '110 days', now() + interval '160 days', now() + interval '161 days', 4, 8, 2500, null, null),
  ('ffffffff-0001-0001-0001-000000000001', 'congressional-app-challenge-2026', 'Congressional App Challenge — CO-02', 'The nation''s premier student computer science competition hosted by Members of the U.S. House of Representatives. Students design and code an application on any platform to address a community or societal need. Colorado District 2 winners are recognized by Rep. Joe Neguse and invited to showcase their app at #HouseOfCode on Capitol Hill.', 'U.S. House of Representatives', 'active', 'national', '2026-27', now() - interval '60 days', now() + interval '40 days', now() + interval '80 days', now() + interval '81 days', 5, 4, 0, 'https://www.congressionalappchallenge.us', null),
  ('ffffffff-0002-0002-0002-000000000002', 'imagine-cup-junior-2027', 'Microsoft Imagine Cup Junior 2027', 'Global artificial intelligence challenge for high school students. Small teams conceptualize ethical AI and machine learning solutions to tackle global issues like climate resilience, accessibility, environmental sustainability, and healthcare using Microsoft Azure AI principles.', 'Microsoft', 'planned', 'world', '2026-27', now() + interval '30 days', now() + interval '160 days', now() + interval '200 days', now() + interval '201 days', 4, 6, 0, 'https://imaginecup.microsoft.com/en-us/junior', null),
  ('ffffffff-0003-0003-0003-000000000003', 'nasa-space-apps-2026', 'NASA International Space Apps Challenge', 'The world''s largest annual global hackathon. Over an intensive 48-hour sprint, multidisciplinary teams leverage NASA''s open Earth and planetary space data to solve real-world challenges spanning climate intelligence, orbital mechanics, geospatial visualization, and robotic exploration.', 'NASA Earth Science Division', 'active', 'world', '2026-27', now() - interval '15 days', now() + interval '25 days', now() + interval '55 days', now() + interval '57 days', 4, 6, 0, 'https://www.spaceappschallenge.org', null),
  ('ffffffff-0004-0004-0004-000000000004', 'picoctf-2027', 'picoCTF Cybersecurity Competition 2027', 'The premier high school cybersecurity and capture-the-flag (CTF) tournament created by Carnegie Mellon University security experts. Teams solve progressively difficult puzzles in binary exploitation, reverse engineering, cryptography, web exploitation, and computer forensics.', 'Carnegie Mellon University', 'planned', 'national', '2026-27', now() + interval '40 days', now() + interval '140 days', now() + interval '160 days', now() + interval '170 days', 5, 5, 0, 'https://picoctf.org', null),
  ('ffffffff-0005-0005-0005-000000000005', 'lemelson-mit-inventeams-2027', 'Lemelson-MIT InvenTeams Grant Initiative', 'A prestigious national initiative providing high school teams up to $7,500 in direct grant funding to invent, engineer, and fabricate working prototypes that solve real-world problems in their local community. The year-long cycle culminates in an invention showcase at MIT EurekaFest in Cambridge, MA.', 'Lemelson-MIT Program', 'planned', 'national', '2026-27', now() + interval '20 days', now() + interval '90 days', now() + interval '240 days', now() + interval '243 days', 1, 15, 0, 'https://lemelson.mit.edu/inventeams', null),
  ('ffffffff-0006-0006-0006-000000000006', 'sourceamerica-design-challenge-2027', 'SourceAmerica Design Challenge 2027', 'A national engineering competition challenging high school students to design, prototype, and test custom assistive workplace devices for individuals with disabilities in their local community. Teams engineer custom jigs, ergonomic fixtures, and electromechanical tools to foster economic autonomy.', 'SourceAmerica', 'planned', 'national', '2026-27', now() + interval '15 days', now() + interval '120 days', now() + interval '170 days', now() + interval '172 days', 3, 6, 0, 'https://www.sourceamerica.org/design-challenge', null),
  ('ffffffff-0007-0007-0007-000000000007', 'conrad-challenge-2027', 'The Conrad Challenge 2026-27', 'A multi-phase global innovation and entrepreneurship competition for teams of 2–5 students across four tracks: Aerospace & Aviation, Cyber-Technology & Security, Energy & Environment, and Health & Nutrition. Finalists travel to NASA''s Kennedy Space Center to pitch their commercially viable innovations to industry titans.', 'Conrad Foundation & Space Center Houston', 'active', 'world', '2026-27', now() - interval '20 days', now() + interval '45 days', now() + interval '190 days', now() + interval '193 days', 3, 5, 0, 'https://www.conradchallenge.org', null),
  ('ffffffff-0008-0008-0008-000000000008', 'nrl-colorado-combat-robotics-2027', 'NRL Colorado — 15 lb Combat Robotics Championship', 'Full-contact, remote-controlled 15 lb combat robot tournament held inside an armored arena in Colorado. Student teams partner with local precision machine shops to mill custom billet aluminum chassis, wire brushless drive systems, tune weapon kinetic energy, and submit a complete engineering design binder.', 'National Robotics League & NTMA Rocky Mountain', 'planned', 'regional', '2026-27', now() + interval '30 days', now() + interval '120 days', now() + interval '175 days', now() + interval '176 days', 3, 8, 15000, 'https://nrlcolorado.org', null),
  ('ffffffff-0009-0009-0009-000000000009', 'cubes-in-space-2027', 'Cubes in Space 2027', 'The only global competition offering students the opportunity to design, fabricate, and test science or engineering experiment payloads contained inside a 40mm cube that are launched into near space and microgravity aboard a NASA sounding rocket or zero-pressure scientific balloon.', 'idoodleDU & NASA Wallops Flight Facility', 'planned', 'world', '2026-27', now() + interval '30 days', now() + interval '130 days', now() + interval '220 days', now() + interval '221 days', 4, 5, 0, 'https://www.cubesinspace.com', null),
  ('ffffffff-0010-0010-0010-000000000010', 'm3-challenge-2027', 'MathWorks Math Modeling (M3) Challenge 2027', 'An intensive 14-hour computational modeling and simulation challenge for high school juniors and seniors. Teams use Python, MATLAB, and mathematical engineering to formulate predictive quantitative solutions for real-world infrastructure and technology questions, competing for >$100k in scholarships.', 'SIAM & MathWorks', 'planned', 'national', '2026-27', now() + interval '35 days', now() + interval '135 days', now() + interval '155 days', now() + interval '156 days', 2, 5, 0, 'https://m3challenge.siam.org', null),
  ('ffffffff-0011-0011-0011-000000000011', 'cserf-isef-pipeline-2027', 'Colorado Science & Engineering Fair (CSERF / ISEF)', 'The premier independent research and prototype development pathway for Colorado students. High school engineers present advanced physical prototypes, embedded systems, and algorithmic architectures through the Boulder Valley Regional Fair, advancing to CSERF at CSU and the Regeneron ISEF International Finals.', 'Society for Science & Colorado State University', 'planned', 'world', '2026-27', now() + interval '25 days', now() + interval '115 days', now() + interval '165 days', now() + interval '167 days', 6, 3, 3500, 'https://www.csef.colostate.edu', null)
on conflict (id) do nothing;


-- 5. Links
insert into links (id, label, url, description, tier, icon, sort_order, is_active)
values
  ('80000001-1111-1111-1111-111111111111', 'Club Discord Server', 'https://discord.gg/engineering-club', 'Our primary real-time communication hub for all subteams, announcements, and voice channels.', 'primary', 'MessageSquare', 1, true),
  ('80000002-2222-2222-2222-222222222222', 'SolidWorks & Altium Student Licenses', 'https://fhs-engineering.org/software-licenses', 'Access student CAD and EDA license keys provided by the engineering department sponsorship.', 'primary', 'Key', 2, true),
  ('80000003-3333-3333-3333-333333333333', 'Makerspace Safety Waiver & Certifications', 'https://safety.fhs-engineering.org/makerspace-waiver', 'Mandatory safety protocol and certification status tracker required before using heavy machinery.', 'primary', 'ShieldAlert', 3, true),
  ('80000004-4444-4444-4444-444444444444', 'Club GitHub Organization', 'https://github.com/fhs-engineering', 'Shared repositories for firmware, ROS2 packages, telemetry dashboards, and hardware designs.', 'primary', 'Github', 4, true),

  ('80000005-5555-5555-5555-555555555555', '3D Print Queue & Material Requests', 'https://3dprint.fhs-engineering.org/queue', 'Submit STL files for Markforged Onyx and Bambu Lab X1-Carbon printers.', 'secondary', 'Printer', 5, true),
  ('80000006-6666-6666-6666-666666666666', 'DigiKey Club Account Discount Portal', 'https://digikey.com/edu/discount', '15% educational discount for club purchases.', 'secondary', 'ShoppingBag', 6, true),
  ('80000007-7777-7777-7777-777777777777', 'Machine Shop Reservation Calendar', 'https://calendar.google.com/calendar/u/0?cid=shop_calendar', 'Book time on the Tormach CNC mill or manual lathe.', 'secondary', 'Calendar', 7, true),

  ('80000008-8888-8888-8888-888888888888', 'Club Constitution & Bylaws 2026-27', 'https://fhs-engineering.org/constitution.pdf', 'Official operational guidelines and election protocols.', 'resource', 'FileText', 8, true),
  ('80000009-9999-9999-9999-999999999999', 'FHS Engineering Travel & Reimbursement Policy', 'https://finance.fhs-engineering.org/travel-rules', 'Standard reimbursement limits for competition lodging and gas.', 'resource', 'Compass', 9, true)
on conflict (id) do nothing;
