-- Seed Data for Engineering Club Website (No Mock Users)

-- 1. Insert Club Settings
insert into club_settings (id, club_name, allowed_email_domain, budget_ceiling_cents)
values ('default', 'Fairview High School Engineering Club', 'bvsd.org', 5000000)
on conflict (id) do nothing;

-- 2. Competitions
-- impact_level: world > national > regional > local (drives directory filter)
insert into competitions (id, slug, name, description, organizer, status, impact_level, season, registration_opens_at, registration_closes_at, event_starts_at, event_ends_at, max_teams, max_team_size, entry_fee_cents, external_url, created_by)
values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'first-robotics-2027', 'FIRST Robotics Competition — BIOCORE 2027', 'The premier international high school robotics challenge. Teams design, CNC-machine, wire, and program industrial-grade 125-lb robots in an intensive build cycle after the January 9, 2027 game reveal. The 2027 BIOCORE season (presented by Haas) explores what sustains life on Earth, culminating at the FIRST Championship in Houston, April 28 – May 1, 2027.', 'FIRST (For Inspiration & Recognition of Science & Technology)', 'active', 'world', '2026-27', now() - interval '30 days', now() + interval '30 days', now() + interval '90 days', now() + interval '94 days', 2, 35, 600000, 'https://www.firstinspires.org/robotics/frc', null),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'nasa-rover-challenge', 'NASA Human Exploration Rover Challenge 2027', 'Design, fabricate, and pilot a human-powered collapsible rover capable of traversing a rugged half-mile simulated lunar and Martian obstacle course at the U.S. Space & Rocket Center in Huntsville, AL (April 21–24, 2027). Teams complete real-time core sampling and equipment deployment while meeting strict telemetry and safety standards.', 'NASA Marshall Space Flight Center', 'active', 'world', '2026-27', now() - interval '20 days', now() + interval '15 days', now() + interval '120 days', now() + interval '124 days', 2, 8, 0, 'https://www.nasa.gov/roverchallenge', null),
  ('cccccccc-cccc-cccc-cccc-cccccccccccc', 'american-rocketry-2027', 'American Rocketry Challenge 2027', 'The world''s largest student rocket contest. Teams engineer and launch model rockets carrying two raw Grade A eggs to exactly 800 feet with a flight duration of 37–40 seconds, returning the payload intact. Registration for the 2027 cycle closes December 6, 2026 ($195/team); National Finals follow in spring 2027.', 'Aerospace Industries Association & NAR', 'planned', 'national', '2026-27', now() + interval '10 days', now() + interval '60 days', now() + interval '180 days', now() + interval '182 days', 3, 10, 19500, 'https://www.rocketrychallenge.org', null),
  ('dddddddd-dddd-dddd-dddd-dddddddddddd', 'solar-car-challenge', 'Solar Car Challenge 2027', 'High school teams design, build, and race full-scale roadworthy solar-electric vehicles. Squads engineer custom roll cages, MPPT solar charging arrays, lithium battery management systems (BMS), and composite aerodynamic fairings. The 2027 cycle returns to the closed-track event at Texas Motor Speedway (July 18–21, 2027); official registration closes March 1.', 'Solar Car Challenge Foundation', 'planned', 'national', '2026-27', now() + interval '20 days', now() + interval '165 days', now() + interval '305 days', now() + interval '308 days', 1, 15, 80000, 'https://www.solarcarchallenge.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 'ftc-biobuzz-2026-27', 'FIRST Tech Challenge — BIOBUZZ 2026-27', 'Head-to-head robotics for smaller teams with a lighter footprint than FRC. The 2026-27 BIOBUZZ season (presented by RTX) kicked off September 12, 2026, challenging teams to design, build, and program robots around a pollination-inspired field game, with judged awards and an engineering portfolio.', 'FIRST (For Inspiration & Recognition of Science & Technology)', 'active', 'world', '2026-27', now() - interval '45 days', now() + interval '45 days', now() + interval '150 days', now() + interval '152 days', 2, 15, 29500, 'https://www.firstinspires.org/robotics/ftc', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeef', 'vex-override-2026-27', 'VEX V5 Robotics Competition — Override', 'The 2026-27 VEX V5RC game "Override" challenges middle and high school teams to design, build, and program competitive robots from the V5 ecosystem. Local qualifiers run November 2026 – February 2027, the US OPEN lands in March, and the World Championship follows in April 2027.', 'Robotics Education & Competition (REC) Foundation', 'active', 'world', '2026-27', now() - interval '40 days', now() + interval '40 days', now() + interval '130 days', now() + interval '132 days', 2, 10, 20000, 'https://www.vexrobotics.com/competition', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1', 'zero-robotics-2026-27', 'MIT Zero Robotics High School Tournament', 'Program NASA SPHERES/Astrobee satellites aboard the International Space Station. Teams write strategy code in C/C++ through online simulation rounds; the season culminates in a live championship aboard the ISS streamed from MIT, judged by astronauts. Registration runs through the fall each year.', 'MIT & NASA', 'active', 'world', '2026-27', now() - interval '25 days', now() + interval '25 days', now() + interval '140 days', now() + interval '141 days', 1, 20, 0, 'https://zerorobotics.mit.edu', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2', 'seaperch-international-2027', 'SeaPerch International Challenge 2027', 'Build and pilot a Remotely Operated underwater Vehicle (ROV) from a standard kit, then compete in in-pool mission courses and technical design reports. Regional qualifiers feed the international championship each spring. A low-cost entry point into marine & ocean engineering.', 'RoboNation / Office of Naval Research', 'active', 'world', '2026-27', now() - interval '15 days', now() + interval '90 days', now() + interval '200 days', now() + interval '202 days', 2, 6, 12500, 'https://seaperch.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3', 'nasa-student-launch-2027', 'NASA Student Launch 2027', 'A nine-month, research-based rocketry challenge mirroring the NASA engineering lifecycle. Teams propose, design, build, and fly high-powered rockets carrying a science payload, passing multiple formal design reviews before Launch Day in Huntsville, AL (April 2027). Application required in the fall.', 'NASA Marshall Space Flight Center', 'active', 'national', '2026-27', now() - interval '10 days', now() + interval '20 days', now() + interval '210 days', now() + interval '213 days', 1, 12, 0, 'https://www.nasa.gov/learning-resources/nasa-student-launch/', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4', 'cyberpatriot-xviii-2026-27', 'CyberPatriot National Youth Cyber Defense Competition', 'The nation''s largest cybersecurity competition, run by the Air & Space Forces Association. Teams act as newly hired IT professionals hardening virtual networks (Windows, Linux, Cisco) against simulated attacks across online rounds, with the top teams advancing to the National Finals in the Washington, D.C. area.', 'Air & Space Forces Association (AFA)', 'active', 'national', '2026-27', now() - interval '35 days', now() + interval '10 days', now() + interval '60 days', now() + interval '61 days', 2, 6, 20500, 'https://www.uscyberpatriot.org', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5', 'tsa-teams-2027', 'TSA TEAMS — Tests of Engineering Aptitude, Math & Science', 'Teams of 4–6 students collaborate on real-world engineering scenarios: a 90-minute multiple-choice exam plus an essay-style design-build portion. State-level competitions feed the national round at the TSA National Conference. Ideal for strong math/science students who want a low-time-commitment competition.', 'Technology Student Association (TSA)', 'planned', 'national', '2026-27', now() + interval '30 days', now() + interval '120 days', now() + interval '150 days', now() + interval '151 days', 2, 6, 12500, 'https://tsaweb.org/teams', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6', 'samsung-solve-2026-27', 'Samsung Solve for Tomorrow 2026-27', 'Use STEM to tackle a real problem in your community. Public-school teams submit project ideas, then develop prototypes with Samsung technology; national winners earn $100,000 prize packages. Runs entirely through the school year with an educator-led application each fall.', 'Samsung Electronics America', 'active', 'national', '2026-27', now() - interval '30 days', now() + interval '60 days', now() + interval '180 days', now() + interval '181 days', 1, 10, 0, 'https://www.samsung.com/us/solvefortomorrow/', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7', 'co-science-bowl-2027', 'Colorado Regional Science Bowl 2027', 'Fast-paced buzzer-style competition covering biology, chemistry, physics, math, and energy technology, hosted by the Department of Energy. Regional winners earn an all-expenses-paid trip to the National Science Bowl in Washington, D.C. Great fit for quiz-bowl-minded engineers.', 'U.S. Department of Energy', 'planned', 'regional', '2026-27', now() + interval '15 days', now() + interval '100 days', now() + interval '140 days', now() + interval '141 days', 2, 5, 0, 'https://science.osti.gov/wdts/nsb', null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee8', 'fhs-maker-sprint-fall-2026', 'FHS Maker Sprint — Fall 2026', 'Our own intra-club design sprint: small teams get a surprise kit of materials and 48 hours to prototype a solution to a secret design brief, judged by local industry mentors. Low stakes, high fun — the best on-ramp for first-year members before committing to a national season.', 'FHS Engineering Club', 'planned', 'local', '2026-27', now() - interval '5 days', now() + interval '12 days', now() + interval '30 days', now() + interval '32 days', 8, 4, 500, null, null),
  ('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9', 'denver-metro-engineering-expo-2027', 'Denver Metro Engineering Expo 2027', 'A regional showcase where Colorado high school engineering teams present projects to judges from local universities and industry — mechanical, aerospace, and civil design tracks with feedback sessions. Strong practice ground for portfolio presentations before national events.', 'Denver Metro STEM Coalition', 'planned', 'regional', '2026-27', now() + interval '45 days', now() + interval '110 days', now() + interval '160 days', now() + interval '161 days', 4, 8, 2500, null, null)
on conflict (id) do nothing;


-- 4. Workshops
insert into workshops (id, slug, title, description, instructor_id, instructor_name, status, starts_at, ends_at, location, capacity, skill_level, materials_url, recording_url, created_by)
values
  ('50000001-1111-1111-1111-111111111111', 'solidworks-advanced-surfacing', 'Mastering Surface Modeling in SolidWorks', 'Deep dive into complex boundary surfaces, lofts, tangency curvature continuity (G2), and ergonomic handheld enclosures.', null, 'Staff Instructor', 'scheduled', now() + interval '3 days' + interval '2 hours', now() + interval '3 days' + interval '4 hours', 'FHS Makerspace & Zoom', 30, 'Intermediate', 'https://github.com/fhs-engineering/solidworks-workshop', null, null),
  ('50000002-2222-2222-2222-222222222222', 'kicad-pcb-design-crashcourse', 'From Schematic to 4-Layer PCB in KiCad', 'Learn component footprint selection, differential pair routing, ground planes, impedance matching, and Gerber export.', null, 'Electronics Lead', 'scheduled', now() + interval '7 days' + interval '3 hours', now() + interval '7 days' + interval '5 hours', 'FHS Electronics Lab', 20, 'Beginner to Intermediate', 'https://github.com/fhs-engineering/kicad-templates', null, null),
  ('50000003-3333-3333-3333-333333333333', 'intro-to-lathe-and-cnc-mill', 'Shop Safety: CNC Mill & Manual Lathe Certification', 'Hands-on safety protocol, feeds & speeds, tooling offset zeroing, and emergency stop operational training.', null, 'Shop Supervisor', 'completed', now() - interval '14 days', now() - interval '14 days' + interval '3 hours', 'FHS Machine Shop', 15, 'All Levels', 'https://fhs-engineering.org/safety-docs', 'https://youtube.com/watch?v=mock-cnc-recording', null)
on conflict (id) do nothing;

-- 5. Links
insert into links (id, label, url, description, tier, icon, sort_order, is_active)
values
  ('80000001-1111-1111-1111-111111111111', 'Club Discord Server', 'https://discord.gg/engineering-club', 'Our primary real-time communication hub for all subteams, announcements, and voice channels.', 'primary', 'MessageSquare', 1, true),
  ('80000002-2222-2222-2222-222222222222', 'SolidWorks & Altium Student Licenses', 'https://fhs-engineering.org/software-licenses', 'Access student CAD and EDA license keys provided by the engineering department sponsorship.', 'primary', 'Key', 2, true),
  ('80000003-3333-3333-3333-333333333333', 'Makerspace Safety Waiver & Certifications', 'https://safety.fhs-engineering.org/makerspace-waiver', 'Mandatory safety protocol and certification status tracker required before using heavy machinery.', 'primary', 'ShieldAlert', 3, true),
  ('80000004-4444-4444-4444-444444444444', 'Club GitHub Organization', 'https://github.com/fhs-engineering', 'Shared repositories for firmware, ROS2 packages, telemetry dashboards, and hardware designs.', 'primary', 'Github', 4, true),

  ('80000005-5555-5555-5555-555555555555', '3D Print Queue & Material Requests', 'https://3dprint.fhs-engineering.org/queue', 'Submit STL files for Markforged Onyx and Bambu Lab X1-Carbon printers.', 'secondary', 'Printer', 5, true),
  ('80000006-6666-6666-6666-666666666666', 'DigiKey Club Account Discount Portal', 'https://digikey.com/edu/discount', '15% educational discount for club purchases.', 'secondary', 'ShoppingBag', 6, true),
  ('80000007-7777-7777-7777-777777777777', 'Machine Shop Reservation Calendar', 'https://calendar.google.com/calendar/u/0?cid=shop_calendar', 'Book time on the Tormach CNC mill or manual lathe.', 'secondary', 'Calendar', 7, true),

  ('80000008-8888-8888-8888-888888888888', 'Club Constitution & Bylaws 2026-27', 'https://fhs-engineering.org/constitution.pdf', 'Official operational guidelines and election protocols.', 'resource', 'FileText', 8, true),
  ('80000009-9999-9999-9999-999999999999', 'FHS Engineering Travel & Reimbursement Policy', 'https://finance.fhs-engineering.org/travel-rules', 'Standard reimbursement limits for competition lodging and gas.', 'resource', 'Compass', 9, true)
on conflict (id) do nothing;
