import type { Database, UserRole, CompStatus, WorkshopStatus, RequestStatus, FundingStatus, LinkTier, TeamRole, WorkLogVisibility } from './types';

export interface AppState {
  profiles: Database['public']['Tables']['profiles']['Row'][];
  competitions: Database['public']['Tables']['competitions']['Row'][];
  teams: Database['public']['Tables']['teams']['Row'][];
  team_members: Database['public']['Tables']['team_members']['Row'][];
  competition_signups: Database['public']['Tables']['competition_signups']['Row'][];
  team_requests: Database['public']['Tables']['team_requests']['Row'][];
  competition_requests: Database['public']['Tables']['competition_requests']['Row'][];
  workshops: Database['public']['Tables']['workshops']['Row'][];
  workshop_rsvps: Database['public']['Tables']['workshop_rsvps']['Row'][];
  workshop_requests: Database['public']['Tables']['workshop_requests']['Row'][];
  workshop_request_votes: Database['public']['Tables']['workshop_request_votes']['Row'][];
  funding_requests: Database['public']['Tables']['funding_requests']['Row'][];
  funding_line_items: Database['public']['Tables']['funding_line_items']['Row'][];
  funding_attachments: Database['public']['Tables']['funding_attachments']['Row'][];
  general_requests: Database['public']['Tables']['general_requests']['Row'][];
  work_logs: Database['public']['Tables']['work_logs']['Row'][];
  links: Database['public']['Tables']['links']['Row'][];
  notifications: Database['public']['Tables']['notifications']['Row'][];
  audit_log: Database['public']['Tables']['audit_log']['Row'][];
  club_settings: Database['public']['Tables']['club_settings']['Row'];
}

export function getInitialMockData(): AppState {
  const now = new Date();

  return {
    general_requests: [],
    club_settings: {
      id: 'default',
      club_name: 'Fairview High School Engineering Club',
      allowed_email_domain: 'bvsd.org',
      budget_ceiling_cents: 5000000,
      updated_at: now.toISOString(),
      updated_by: null,
    },
    profiles: [],
    competitions: [
      {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        slug: 'first-robotics-2027',
        name: 'FIRST Robotics Competition — BIOCORE 2027',
        description: 'The premier international high school robotics challenge. Teams design, CNC-machine, wire, and program industrial-grade 125-lb robots in an intensive build cycle after the January 9, 2027 game reveal. The 2027 BIOCORE season (presented by Haas) explores what sustains life on Earth, culminating at the FIRST Championship in Houston, April 28 – May 1, 2027.',
        organizer: 'FIRST (For Inspiration & Recognition of Science & Technology)',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 90 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 94 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 35,
        entry_fee_cents: 600000,
        external_url: 'https://www.firstinspires.org/robotics/frc',
        created_by: null,
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        slug: 'nasa-rover-challenge',
        name: 'NASA Human Exploration Rover Challenge 2027',
        description: 'Design, fabricate, and pilot a human-powered collapsible rover capable of traversing a rugged half-mile simulated lunar and Martian obstacle course at the U.S. Space & Rocket Center in Huntsville, AL (April 21–24, 2027). Teams complete real-time core sampling and equipment deployment while meeting strict telemetry and safety standards.',
        organizer: 'NASA Marshall Space Flight Center',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 124 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 8,
        entry_fee_cents: 0,
        external_url: 'https://www.nasa.gov/roverchallenge',
        created_by: null,
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
        slug: 'american-rocketry-2027',
        name: 'American Rocketry Challenge 2027',
        description: "The world's largest student rocket contest. Teams engineer and launch model rockets carrying two raw Grade A eggs to exactly 800 feet with a flight duration of 37–40 seconds, returning the payload intact. Registration for the 2027 cycle closes December 6, 2026 ($195/team); National Finals follow in spring 2027.",
        organizer: 'Aerospace Industries Association & NAR',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 10 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 180 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 182 * 86400000).toISOString(),
        max_teams: 3,
        max_team_size: 10,
        entry_fee_cents: 19500,
        external_url: 'https://www.rocketrychallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
        slug: 'solar-car-challenge',
        name: 'Solar Car Challenge 2027',
        description: 'High school teams design, build, and race full-scale roadworthy solar-electric vehicles. Squads engineer custom roll cages, MPPT solar charging arrays, lithium battery management systems (BMS), and composite aerodynamic fairings. The 2027 cycle returns to the closed-track event at Texas Motor Speedway (July 18–21, 2027); official registration closes March 1.',
        organizer: 'Solar Car Challenge Foundation',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 165 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 305 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 308 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 15,
        entry_fee_cents: 80000,
        external_url: 'https://www.solarcarchallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 310 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
        slug: 'ftc-biobuzz-2026-27',
        name: 'FIRST Tech Challenge — BIOBUZZ 2026-27',
        description: 'Head-to-head robotics for smaller teams with a lighter footprint than FRC. The 2026-27 BIOBUZZ season (presented by RTX) kicked off September 12, 2026, challenging teams to design, build, and program robots around a pollination-inspired field game, with judged awards and an engineering portfolio.',
        organizer: 'FIRST (For Inspiration & Recognition of Science & Technology)',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 45 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 150 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 152 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 15,
        entry_fee_cents: 29500,
        external_url: 'https://www.firstinspires.org/robotics/ftc',
        created_by: null,
        created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeef',
        slug: 'vex-override-2026-27',
        name: 'VEX V5 Robotics Competition — Override',
        description: 'The 2026-27 VEX V5RC game "Override" challenges middle and high school teams to design, build, and program competitive robots from the V5 ecosystem. Local qualifiers run November 2026 – February 2027, the US OPEN lands in March, and the World Championship follows in April 2027.',
        organizer: 'Robotics Education & Competition (REC) Foundation',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 40 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 40 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 130 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 132 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 10,
        entry_fee_cents: 20000,
        external_url: 'https://www.vexrobotics.com/competition',
        created_by: null,
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1',
        slug: 'zero-robotics-2026-27',
        name: 'MIT Zero Robotics High School Tournament',
        description: 'Program NASA SPHERES/Astrobee satellites aboard the International Space Station. Teams write strategy code in C/C++ through online simulation rounds; the season culminates in a live championship aboard the ISS streamed from MIT, judged by astronauts. Registration runs through the fall each year.',
        organizer: 'MIT & NASA',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 25 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 140 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 141 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 20,
        entry_fee_cents: 0,
        external_url: 'https://zerorobotics.mit.edu',
        created_by: null,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2',
        slug: 'seaperch-international-2027',
        name: 'SeaPerch International Challenge 2027',
        description: 'Build and pilot a Remotely Operated underwater Vehicle (ROV) from a standard kit, then compete in in-pool mission courses and technical design reports. Regional qualifiers feed the international championship each spring. A low-cost entry point into marine & ocean engineering.',
        organizer: 'RoboNation / Office of Naval Research',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 90 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 200 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 202 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 12500,
        external_url: 'https://seaperch.org',
        created_by: null,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3',
        slug: 'nasa-student-launch-2027',
        name: 'NASA Student Launch 2027',
        description: 'A nine-month, research-based rocketry challenge mirroring the NASA engineering lifecycle. Teams propose, design, build, and fly high-powered rockets carrying a science payload, passing multiple formal design reviews before Launch Day in Huntsville, AL (April 2027). Application required in the fall.',
        organizer: 'NASA Marshall Space Flight Center',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 20 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 210 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 213 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 12,
        entry_fee_cents: 0,
        external_url: 'https://www.nasa.gov/learning-resources/nasa-student-launch/',
        created_by: null,
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4',
        slug: 'cyberpatriot-xviii-2026-27',
        name: 'CyberPatriot National Youth Cyber Defense Competition',
        description: "The nation's largest cybersecurity competition, run by the Air & Space Forces Association. Teams act as newly hired IT professionals hardening virtual networks (Windows, Linux, Cisco) against simulated attacks across online rounds, with the top teams advancing to the National Finals in the Washington, D.C. area.",
        organizer: 'Air & Space Forces Association (AFA)',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 10 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 61 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 20500,
        external_url: 'https://www.uscyberpatriot.org',
        created_by: null,
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5',
        slug: 'tsa-teams-2027',
        name: 'TSA TEAMS — Tests of Engineering Aptitude, Math & Science',
        description: 'Teams of 4–6 students collaborate on real-world engineering scenarios: a 90-minute multiple-choice exam plus an essay-style design-build portion. State-level competitions feed the national round at the TSA National Conference. Ideal for strong math/science students who want a low-time-commitment competition.',
        organizer: 'Technology Student Association (TSA)',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 150 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 151 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 12500,
        external_url: 'https://tsaweb.org/teams',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6',
        slug: 'samsung-solve-2026-27',
        name: 'Samsung Solve for Tomorrow 2026-27',
        description: 'Use STEM to tackle a real problem in your community. Public-school teams submit project ideas, then develop prototypes with Samsung technology; national winners earn $100,000 prize packages. Runs entirely through the school year with an educator-led application each fall.',
        organizer: 'Samsung Electronics America',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 180 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 181 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 10,
        entry_fee_cents: 0,
        external_url: 'https://www.samsung.com/us/solvefortomorrow/',
        created_by: null,
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7',
        slug: 'co-science-bowl-2027',
        name: 'Colorado Regional Science Bowl 2027',
        description: 'Fast-paced buzzer-style competition covering biology, chemistry, physics, math, and energy technology, hosted by the Department of Energy. Regional winners earn an all-expenses-paid trip to the National Science Bowl in Washington, D.C. Great fit for quiz-bowl-minded engineers.',
        organizer: 'U.S. Department of Energy',
        status: 'planned',
        impact_level: 'regional',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 100 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 140 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 141 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://science.osti.gov/wdts/nsb',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9',
        slug: 'denver-metro-engineering-expo-2027',
        name: 'Denver Metro Engineering Expo 2027',
        description: 'A regional showcase where Colorado high school engineering teams present projects to judges from local universities and industry — mechanical, aerospace, and civil design tracks with feedback sessions. Strong practice ground for portfolio presentations before national events.',
        organizer: 'Denver Metro STEM Coalition',
        status: 'planned',
        impact_level: 'regional',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 45 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 110 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 160 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 161 * 86400000).toISOString(),
        max_teams: 4,
        max_team_size: 8,
        entry_fee_cents: 2500,
        external_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0001-0001-0001-000000000001',
        slug: 'congressional-app-challenge-2026',
        name: 'Congressional App Challenge — CO-02',
        description:
          "The nation's premier student computer science competition hosted by Members of the U.S. House of Representatives. Students design and code an application on any platform to address a community or societal need. Colorado District 2 winners are recognized by Rep. Joe Neguse and invited to showcase their app at #HouseOfCode on Capitol Hill.",
        organizer: 'U.S. House of Representatives',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 60 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 40 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 80 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 81 * 86400000).toISOString(),
        max_teams: 5,
        max_team_size: 4,
        entry_fee_cents: 0,
        external_url: 'https://www.congressionalappchallenge.us',
        created_by: null,
        created_at: new Date(Date.now() - 65 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0002-0002-0002-000000000002',
        slug: 'imagine-cup-junior-2027',
        name: 'Microsoft Imagine Cup Junior 2027',
        description:
          'Global artificial intelligence challenge for high school students. Small teams conceptualize ethical AI and machine learning solutions to tackle global issues like climate resilience, accessibility, environmental sustainability, and healthcare using Microsoft Azure AI principles.',
        organizer: 'Microsoft',
        status: 'planned',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 160 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 200 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 201 * 86400000).toISOString(),
        max_teams: 4,
        max_team_size: 6,
        entry_fee_cents: 0,
        external_url: 'https://imaginecup.microsoft.com/en-us/junior',
        created_by: null,
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0003-0003-0003-000000000003',
        slug: 'nasa-space-apps-2026',
        name: 'NASA International Space Apps Challenge',
        description:
          "The world's largest annual global hackathon. Over an intensive 48-hour sprint, multidisciplinary teams leverage NASA's open Earth and planetary space data to solve real-world challenges spanning climate intelligence, orbital mechanics, geospatial visualization, and robotic exploration.",
        organizer: 'NASA Earth Science Division',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 25 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 55 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 57 * 86400000).toISOString(),
        max_teams: 4,
        max_team_size: 6,
        entry_fee_cents: 0,
        external_url: 'https://www.spaceappschallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0004-0004-0004-000000000004',
        slug: 'picoctf-2027',
        name: 'picoCTF Cybersecurity Competition 2027',
        description:
          'The premier high school cybersecurity and capture-the-flag (CTF) tournament created by Carnegie Mellon University security experts. Teams solve progressively difficult puzzles in binary exploitation, reverse engineering, cryptography, web exploitation, and computer forensics.',
        organizer: 'Carnegie Mellon University',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 40 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 140 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 160 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 170 * 86400000).toISOString(),
        max_teams: 5,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://picoctf.org',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0005-0005-0005-000000000005',
        slug: 'lemelson-mit-inventeams-2027',
        name: 'Lemelson-MIT InvenTeams Grant Initiative',
        description:
          'A prestigious national initiative providing high school teams up to $7,500 in direct grant funding to invent, engineer, and fabricate working prototypes that solve real-world problems in their local community. The year-long cycle culminates in an invention showcase at MIT EurekaFest in Cambridge, MA.',
        organizer: 'Lemelson-MIT Program',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 90 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 240 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 243 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 15,
        entry_fee_cents: 0,
        external_url: 'https://lemelson.mit.edu/inventeams',
        created_by: null,
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0006-0006-0006-000000000006',
        slug: 'sourceamerica-design-challenge-2027',
        name: 'SourceAmerica Design Challenge 2027',
        description:
          'A national engineering competition challenging high school students to design, prototype, and test custom assistive workplace devices for individuals with disabilities in their local community. Teams engineer custom jigs, ergonomic fixtures, and electromechanical tools to foster economic autonomy.',
        organizer: 'SourceAmerica',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 170 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 172 * 86400000).toISOString(),
        max_teams: 3,
        max_team_size: 6,
        entry_fee_cents: 0,
        external_url: 'https://www.sourceamerica.org/design-challenge',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0007-0007-0007-000000000007',
        slug: 'conrad-challenge-2027',
        name: 'The Conrad Challenge 2026-27',
        description:
          "A multi-phase global innovation and entrepreneurship competition for teams of 2–5 students across four tracks: Aerospace & Aviation, Cyber-Technology & Security, Energy & Environment, and Health & Nutrition. Finalists travel to NASA's Kennedy Space Center to pitch their commercially viable innovations to industry titans.",
        organizer: 'Conrad Foundation & Space Center Houston',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 45 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 190 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 193 * 86400000).toISOString(),
        max_teams: 3,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://www.conradchallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0008-0008-0008-000000000008',
        slug: 'nrl-colorado-combat-robotics-2027',
        name: 'NRL Colorado — 15 lb Combat Robotics Championship',
        description:
          'Full-contact, remote-controlled 15 lb combat robot tournament held inside an armored arena in Colorado. Student teams partner with local precision machine shops to mill custom billet aluminum chassis, wire brushless drive systems, tune weapon kinetic energy, and submit a complete engineering design binder.',
        organizer: 'National Robotics League & NTMA Rocky Mountain',
        status: 'planned',
        impact_level: 'regional',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 175 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 176 * 86400000).toISOString(),
        max_teams: 3,
        max_team_size: 8,
        entry_fee_cents: 15000,
        external_url: 'https://nrlcolorado.org',
        created_by: null,
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0009-0009-0009-000000000009',
        slug: 'cubes-in-space-2027',
        name: 'Cubes in Space 2027',
        description:
          'The only global competition offering students the opportunity to design, fabricate, and test science or engineering experiment payloads contained inside a 40mm cube that are launched into near space and microgravity aboard a NASA sounding rocket or zero-pressure scientific balloon.',
        organizer: 'idoodleDU & NASA Wallops Flight Facility',
        status: 'planned',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 130 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 220 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 221 * 86400000).toISOString(),
        max_teams: 4,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://www.cubesinspace.com',
        created_by: null,
        created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0010-0010-0010-000000000010',
        slug: 'm3-challenge-2027',
        name: 'MathWorks Math Modeling (M3) Challenge 2027',
        description:
          'An intensive 14-hour computational modeling and simulation challenge for high school juniors and seniors. Teams use Python, MATLAB, and mathematical engineering to formulate predictive quantitative solutions for real-world infrastructure and technology questions, competing for >$100k in scholarships.',
        organizer: 'SIAM & MathWorks',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 35 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 135 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 155 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 156 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://m3challenge.siam.org',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'ffffffff-0011-0011-0011-000000000011',
        slug: 'cserf-isef-pipeline-2027',
        name: 'Colorado Science & Engineering Fair (CSERF / ISEF)',
        description:
          'The premier independent research and prototype development pathway for Colorado students. High school engineers present advanced physical prototypes, embedded systems, and algorithmic architectures through the Boulder Valley Regional Fair, advancing to CSERF at CSU and the Regeneron ISEF International Finals.',
        organizer: 'Society for Science & Colorado State University',
        status: 'planned',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 25 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 115 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 165 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 167 * 86400000).toISOString(),
        max_teams: 6,
        max_team_size: 3,
        entry_fee_cents: 3500,
        external_url: 'https://www.csef.colostate.edu',
        created_by: null,
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    teams: [],
    team_members: [],
    competition_signups: [],
    team_requests: [],
    workshops: [],
    competition_requests: [],
    workshop_rsvps: [],
    workshop_requests: [],
    workshop_request_votes: [],
    funding_requests: [],
    funding_line_items: [],
    funding_attachments: [],
    work_logs: [],
    links: [
      {
        id: '80000001-1111-1111-1111-111111111111',
        label: 'Club Discord Server',
        url: 'https://discord.gg/engineering-club',
        description: 'Our primary real-time communication hub for all subteams, announcements, and voice channels.',
        tier: 'primary',
        icon: 'MessageSquare',
        sort_order: 1,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000002-2222-2222-2222-222222222222',
        label: 'SolidWorks & Altium Student Licenses',
        url: 'https://fhs-engineering.org/software-licenses',
        description: 'Access student CAD and EDA license keys provided by the engineering department sponsorship.',
        tier: 'primary',
        icon: 'Key',
        sort_order: 2,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000003-3333-3333-3333-333333333333',
        label: 'Makerspace Safety Waiver & Certifications',
        url: 'https://safety.fhs-engineering.org/makerspace-waiver',
        description: 'Mandatory safety protocol and certification status tracker required before using heavy machinery.',
        tier: 'primary',
        icon: 'ShieldAlert',
        sort_order: 3,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000004-4444-4444-4444-444444444444',
        label: 'Club GitHub Organization',
        url: 'https://github.com/fhs-engineering',
        description: 'Shared repositories for firmware, ROS2 packages, telemetry dashboards, and hardware designs.',
        tier: 'primary',
        icon: 'Github',
        sort_order: 4,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000005-5555-5555-5555-555555555555',
        label: '3D Print Queue & Material Requests',
        url: 'https://3dprint.fhs-engineering.org/queue',
        description: 'Submit STL files for Markforged Onyx and Bambu Lab X1-Carbon printers.',
        tier: 'secondary',
        icon: 'Printer',
        sort_order: 5,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000006-6666-6666-6666-666666666666',
        label: 'DigiKey Club Account Discount Portal',
        url: 'https://digikey.com/edu/discount',
        description: '15% educational discount for club purchases.',
        tier: 'secondary',
        icon: 'ShoppingBag',
        sort_order: 6,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000007-7777-7777-7777-777777777777',
        label: 'Machine Shop Reservation Calendar',
        url: 'https://calendar.google.com/calendar/u/0?cid=shop_calendar',
        description: 'Book time on the Tormach CNC mill or manual lathe.',
        tier: 'secondary',
        icon: 'Calendar',
        sort_order: 7,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000008-8888-8888-8888-888888888888',
        label: 'Club Constitution & Bylaws 2026-27',
        url: 'https://fhs-engineering.org/constitution.pdf',
        description: 'Official operational guidelines and election protocols.',
        tier: 'resource',
        icon: 'FileText',
        sort_order: 8,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000009-9999-9999-9999-999999999999',
        label: 'FHS Engineering Travel & Reimbursement Policy',
        url: 'https://finance.fhs-engineering.org/travel-rules',
        description: 'Standard reimbursement limits for competition lodging and gas.',
        tier: 'resource',
        icon: 'Compass',
        sort_order: 9,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
    ],
    notifications: [],
    audit_log: [],
  };
}

// The store must live on globalThis: Next.js bundles this module separately per
// route, so a module-level variable would give every page its own isolated copy
// (breaking sessions and any cross-route state). globalThis is shared per process.
const GLOBAL_STORE_KEY = '__fhs_engineering_app_state__';

function readGlobalStore(): AppState | null {
  return ((globalThis as any)[GLOBAL_STORE_KEY] as AppState | undefined) ?? null;
}

function writeGlobalStore(store: AppState) {
  (globalThis as any)[GLOBAL_STORE_KEY] = store;
}

export function getDb(): AppState {
  let store = readGlobalStore();
  if (!store) {
    store = getInitialMockData();
    writeGlobalStore(store);
  }
  return store;
}

export function resetDb() {
  const store = getInitialMockData();
  writeGlobalStore(store);
  return store;
}
