import type { Database, UserRole, CompStatus, WorkshopStatus, RequestStatus, FundingStatus, LinkTier, TeamRole, WorkLogVisibility } from './types';

export interface AppState {
  profiles: Database['public']['Tables']['profiles']['Row'][];
  competitions: Database['public']['Tables']['competitions']['Row'][];
  teams: Database['public']['Tables']['teams']['Row'][];
  team_members: Database['public']['Tables']['team_members']['Row'][];
  competition_signups: Database['public']['Tables']['competition_signups']['Row'][];
  team_requests: Database['public']['Tables']['team_requests']['Row'][];
  competition_requests: Database['public']['Tables']['competition_requests']['Row'][];
  workshops: Database['public']['Tables']['workshops']['Row'][];
  workshop_rsvps: Database['public']['Tables']['workshop_rsvps']['Row'][];
  workshop_requests: Database['public']['Tables']['workshop_requests']['Row'][];
  workshop_request_votes: Database['public']['Tables']['workshop_request_votes']['Row'][];
  funding_requests: Database['public']['Tables']['funding_requests']['Row'][];
  funding_line_items: Database['public']['Tables']['funding_line_items']['Row'][];
  funding_attachments: Database['public']['Tables']['funding_attachments']['Row'][];
  general_requests: Database['public']['Tables']['general_requests']['Row'][];
  work_logs: Database['public']['Tables']['work_logs']['Row'][];
  links: Database['public']['Tables']['links']['Row'][];
  notifications: Database['public']['Tables']['notifications']['Row'][];
  audit_log: Database['public']['Tables']['audit_log']['Row'][];
  club_settings: Database['public']['Tables']['club_settings']['Row'];
}

export function getInitialMockData(): AppState {
  const now = new Date();

  return {
    general_requests: [],
    club_settings: {
      id: 'default',
      club_name: 'Fairview High School Engineering Club',
      allowed_email_domain: 'bvsd.org',
      budget_ceiling_cents: 5000000,
      updated_at: now.toISOString(),
      updated_by: null,
    },
    profiles: [],
    competitions: [
      {
        id: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        slug: 'first-robotics-2027',
        name: 'FIRST Robotics Competition — BIOCORE 2027',
        description: 'The premier international high school robotics challenge. Teams design, CNC-machine, wire, and program industrial-grade 125-lb robots in an intensive build cycle after the January 9, 2027 game reveal. The 2027 BIOCORE season (presented by Haas) explores what sustains life on Earth, culminating at the FIRST Championship in Houston, April 28 – May 1, 2027.',
        organizer: 'FIRST (For Inspiration & Recognition of Science & Technology)',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 90 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 94 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 35,
        entry_fee_cents: 600000,
        external_url: 'https://www.firstinspires.org/robotics/frc',
        created_by: null,
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        slug: 'nasa-rover-challenge',
        name: 'NASA Human Exploration Rover Challenge 2027',
        description: 'Design, fabricate, and pilot a human-powered collapsible rover capable of traversing a rugged half-mile simulated lunar and Martian obstacle course at the U.S. Space & Rocket Center in Huntsville, AL (April 21–24, 2027). Teams complete real-time core sampling and equipment deployment while meeting strict telemetry and safety standards.',
        organizer: 'NASA Marshall Space Flight Center',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 124 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 8,
        entry_fee_cents: 0,
        external_url: 'https://www.nasa.gov/roverchallenge',
        created_by: null,
        created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'cccccccc-cccc-cccc-cccc-cccccccccccc',
        slug: 'american-rocketry-2027',
        name: 'American Rocketry Challenge 2027',
        description: "The world's largest student rocket contest. Teams engineer and launch model rockets carrying two raw Grade A eggs to exactly 800 feet with a flight duration of 37–40 seconds, returning the payload intact. Registration for the 2027 cycle closes December 6, 2026 ($195/team); National Finals follow in spring 2027.",
        organizer: 'Aerospace Industries Association & NAR',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 10 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 180 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 182 * 86400000).toISOString(),
        max_teams: 3,
        max_team_size: 10,
        entry_fee_cents: 19500,
        external_url: 'https://www.rocketrychallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
        slug: 'solar-car-challenge',
        name: 'Solar Car Challenge 2027',
        description: 'High school teams design, build, and race full-scale roadworthy solar-electric vehicles. Squads engineer custom roll cages, MPPT solar charging arrays, lithium battery management systems (BMS), and composite aerodynamic fairings. The 2027 cycle returns to the closed-track event at Texas Motor Speedway (July 18–21, 2027); official registration closes March 1.',
        organizer: 'Solar Car Challenge Foundation',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 20 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 165 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 305 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 308 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 15,
        entry_fee_cents: 80000,
        external_url: 'https://www.solarcarchallenge.org',
        created_by: null,
        created_at: new Date(Date.now() - 310 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
        slug: 'ftc-biobuzz-2026-27',
        name: 'FIRST Tech Challenge — BIOBUZZ 2026-27',
        description: 'Head-to-head robotics for smaller teams with a lighter footprint than FRC. The 2026-27 BIOBUZZ season (presented by RTX) kicked off September 12, 2026, challenging teams to design, build, and program robots around a pollination-inspired field game, with judged awards and an engineering portfolio.',
        organizer: 'FIRST (For Inspiration & Recognition of Science & Technology)',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 45 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 150 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 152 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 15,
        entry_fee_cents: 29500,
        external_url: 'https://www.firstinspires.org/robotics/ftc',
        created_by: null,
        created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeef',
        slug: 'vex-override-2026-27',
        name: 'VEX V5 Robotics Competition — Override',
        description: 'The 2026-27 VEX V5RC game "Override" challenges middle and high school teams to design, build, and program competitive robots from the V5 ecosystem. Local qualifiers run November 2026 – February 2027, the US OPEN lands in March, and the World Championship follows in April 2027.',
        organizer: 'Robotics Education & Competition (REC) Foundation',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 40 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 40 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 130 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 132 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 10,
        entry_fee_cents: 20000,
        external_url: 'https://www.vexrobotics.com/competition',
        created_by: null,
        created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1',
        slug: 'zero-robotics-2026-27',
        name: 'MIT Zero Robotics High School Tournament',
        description: 'Program NASA SPHERES/Astrobee satellites aboard the International Space Station. Teams write strategy code in C/C++ through online simulation rounds; the season culminates in a live championship aboard the ISS streamed from MIT, judged by astronauts. Registration runs through the fall each year.',
        organizer: 'MIT & NASA',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 25 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 25 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 140 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 141 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 20,
        entry_fee_cents: 0,
        external_url: 'https://zerorobotics.mit.edu',
        created_by: null,
        created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee2',
        slug: 'seaperch-international-2027',
        name: 'SeaPerch International Challenge 2027',
        description: 'Build and pilot a Remotely Operated underwater Vehicle (ROV) from a standard kit, then compete in in-pool mission courses and technical design reports. Regional qualifiers feed the international championship each spring. A low-cost entry point into marine & ocean engineering.',
        organizer: 'RoboNation / Office of Naval Research',
        status: 'active',
        impact_level: 'world',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 90 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 200 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 202 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 12500,
        external_url: 'https://seaperch.org',
        created_by: null,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee3',
        slug: 'nasa-student-launch-2027',
        name: 'NASA Student Launch 2027',
        description: 'A nine-month, research-based rocketry challenge mirroring the NASA engineering lifecycle. Teams propose, design, build, and fly high-powered rockets carrying a science payload, passing multiple formal design reviews before Launch Day in Huntsville, AL (April 2027). Application required in the fall.',
        organizer: 'NASA Marshall Space Flight Center',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 10 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 20 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 210 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 213 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 12,
        entry_fee_cents: 0,
        external_url: 'https://www.nasa.gov/learning-resources/nasa-student-launch/',
        created_by: null,
        created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee4',
        slug: 'cyberpatriot-xviii-2026-27',
        name: 'CyberPatriot National Youth Cyber Defense Competition',
        description: "The nation's largest cybersecurity competition, run by the Air & Space Forces Association. Teams act as newly hired IT professionals hardening virtual networks (Windows, Linux, Cisco) against simulated attacks across online rounds, with the top teams advancing to the National Finals in the Washington, D.C. area.",
        organizer: 'Air & Space Forces Association (AFA)',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 10 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 61 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 20500,
        external_url: 'https://www.uscyberpatriot.org',
        created_by: null,
        created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5',
        slug: 'tsa-teams-2027',
        name: 'TSA TEAMS — Tests of Engineering Aptitude, Math & Science',
        description: 'Teams of 4–6 students collaborate on real-world engineering scenarios: a 90-minute multiple-choice exam plus an essay-style design-build portion. State-level competitions feed the national round at the TSA National Conference. Ideal for strong math/science students who want a low-time-commitment competition.',
        organizer: 'Technology Student Association (TSA)',
        status: 'planned',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 120 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 150 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 151 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 6,
        entry_fee_cents: 12500,
        external_url: 'https://tsaweb.org/teams',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6',
        slug: 'samsung-solve-2026-27',
        name: 'Samsung Solve for Tomorrow 2026-27',
        description: 'Use STEM to tackle a real problem in your community. Public-school teams submit project ideas, then develop prototypes with Samsung technology; national winners earn $100,000 prize packages. Runs entirely through the school year with an educator-led application each fall.',
        organizer: 'Samsung Electronics America',
        status: 'active',
        impact_level: 'national',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 30 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 60 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 180 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 181 * 86400000).toISOString(),
        max_teams: 1,
        max_team_size: 10,
        entry_fee_cents: 0,
        external_url: 'https://www.samsung.com/us/solvefortomorrow/',
        created_by: null,
        created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee7',
        slug: 'co-science-bowl-2027',
        name: 'Colorado Regional Science Bowl 2027',
        description: 'Fast-paced buzzer-style competition covering biology, chemistry, physics, math, and energy technology, hosted by the Department of Energy. Regional winners earn an all-expenses-paid trip to the National Science Bowl in Washington, D.C. Great fit for quiz-bowl-minded engineers.',
        organizer: 'U.S. Department of Energy',
        status: 'planned',
        impact_level: 'regional',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 15 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 100 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 140 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 141 * 86400000).toISOString(),
        max_teams: 2,
        max_team_size: 5,
        entry_fee_cents: 0,
        external_url: 'https://science.osti.gov/wdts/nsb',
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee8',
        slug: 'fhs-maker-sprint-fall-2026',
        name: 'FHS Maker Sprint — Fall 2026',
        description: 'Our own intra-club design sprint: small teams get a surprise kit of materials and 48 hours to prototype a solution to a secret design brief, judged by local industry mentors. Low stakes, high fun — the best on-ramp for first-year members before committing to a national season.',
        organizer: 'FHS Engineering Club',
        status: 'planned',
        impact_level: 'local',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 12 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 30 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 32 * 86400000).toISOString(),
        max_teams: 8,
        max_team_size: 4,
        entry_fee_cents: 500,
        external_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9',
        slug: 'denver-metro-engineering-expo-2027',
        name: 'Denver Metro Engineering Expo 2027',
        description: 'A regional showcase where Colorado high school engineering teams present projects to judges from local universities and industry — mechanical, aerospace, and civil design tracks with feedback sessions. Strong practice ground for portfolio presentations before national events.',
        organizer: 'Denver Metro STEM Coalition',
        status: 'planned',
        impact_level: 'regional',
        season: '2026-27',
        registration_opens_at: new Date(Date.now() + 45 * 86400000).toISOString(),
        registration_closes_at: new Date(Date.now() + 110 * 86400000).toISOString(),
        event_starts_at: new Date(Date.now() + 160 * 86400000).toISOString(),
        event_ends_at: new Date(Date.now() + 161 * 86400000).toISOString(),
        max_teams: 4,
        max_team_size: 8,
        entry_fee_cents: 2500,
        external_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    teams: [],
    team_members: [],
    competition_signups: [],
    team_requests: [],
    workshops: [
      {
        id: '50000001-1111-1111-1111-111111111111',
        slug: 'solidworks-advanced-surfacing',
        title: 'Mastering Surface Modeling in SolidWorks',
        description: 'Deep dive into complex boundary surfaces, lofts, tangency curvature continuity (G2), and ergonomic handheld enclosures.',
        instructor_id: null,
        instructor_name: 'Staff Instructor',
        status: 'scheduled',
        starts_at: new Date(Date.now() + 5 * 86400000 + 2 * 3600000).toISOString(),
        ends_at: new Date(Date.now() + 5 * 86400000 + 4 * 3600000).toISOString(),
        location: 'FHS Makerspace Room 604 & Zoom',
        capacity: 30,
        skill_level: 'Intermediate',
        materials_url: 'https://github.com/fhs-engineering/solidworks-workshop',
        recording_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '50000002-2222-2222-2222-222222222222',
        slug: 'kicad-pcb-design-crashcourse',
        title: 'From Schematic to 4-Layer PCB in KiCad',
        description: 'Learn component footprint selection, differential pair routing, ground planes, impedance matching, and Gerber export.',
        instructor_id: null,
        instructor_name: 'Electronics Lead',
        status: 'scheduled',
        starts_at: new Date(Date.now() + 8 * 86400000 + 3 * 3600000).toISOString(),
        ends_at: new Date(Date.now() + 8 * 86400000 + 5 * 3600000).toISOString(),
        location: 'FHS Electronics Bay 102',
        capacity: 20,
        skill_level: 'Beginner to Intermediate',
        materials_url: 'https://github.com/fhs-engineering/kicad-templates',
        recording_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '50000004-4444-4444-4444-444444444444',
        slug: 'bambu-3d-printing-certification',
        title: 'Bambu Lab X1-Carbon & Markforged Onyx Slicing Clearance',
        description: 'Hands-on training for high-temp CF filament slicing, multi-color AMS setup, tolerance tuning, and makerspace print queue clearance.',
        instructor_id: null,
        instructor_name: 'Makerspace Lead',
        status: 'scheduled',
        starts_at: new Date(Date.now() + 12 * 86400000 + 1 * 3600000).toISOString(),
        ends_at: new Date(Date.now() + 12 * 86400000 + 3 * 3600000).toISOString(),
        location: 'Room 604 Rapid Prototyping Bay',
        capacity: 25,
        skill_level: 'All Levels',
        materials_url: 'https://fhs-engineering.org/3dprint-guide',
        recording_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '50000005-5555-5555-5555-555555555555',
        slug: 'frc-swerve-vision-lab',
        title: 'FRC 2027 Swerve Drive Kinematics & Vision Targeting Lab',
        description: 'Practical tuning of SDS MK4i swerve modules, PID feedback loops, and AprilTag pose estimation with PhotonVision.',
        instructor_id: null,
        instructor_name: 'FRC Software Captain',
        status: 'scheduled',
        starts_at: new Date(Date.now() + 18 * 86400000 + 4 * 3600000).toISOString(),
        ends_at: new Date(Date.now() + 18 * 86400000 + 6 * 3600000).toISOString(),
        location: 'Robotics Arena / FHS Shop',
        capacity: 35,
        skill_level: 'Advanced',
        materials_url: 'https://github.com/fhs-engineering/frc-swerve-2027',
        recording_url: null,
        created_by: null,
        created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
      {
        id: '50000003-3333-3333-3333-333333333333',
        slug: 'intro-to-lathe-and-cnc-mill',
        title: 'Shop Safety: CNC Mill & Manual Lathe Certification',
        description: 'Hands-on safety protocol, feeds & speeds, tooling offset zeroing, and emergency stop operational training.',
        instructor_id: null,
        instructor_name: 'Shop Supervisor',
        status: 'completed',
        starts_at: new Date(Date.now() - 14 * 86400000).toISOString(),
        ends_at: new Date(Date.now() - 14 * 86400000 + 3 * 3600000).toISOString(),
        location: 'FHS Machine Shop',
        capacity: 15,
        skill_level: 'All Levels',
        materials_url: 'https://fhs-engineering.org/safety-docs',
        recording_url: 'https://youtube.com/watch?v=mock-cnc-recording',
        created_by: null,
        created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
        updated_at: new Date().toISOString(),
      },
    ],
    competition_requests: [],
    workshop_rsvps: [],
    workshop_requests: [],
    workshop_request_votes: [],
    funding_requests: [],
    funding_line_items: [],
    funding_attachments: [],
    work_logs: [],
    links: [
      {
        id: '80000001-1111-1111-1111-111111111111',
        label: 'Club Discord Server',
        url: 'https://discord.gg/engineering-club',
        description: 'Our primary real-time communication hub for all subteams, announcements, and voice channels.',
        tier: 'primary',
        icon: 'MessageSquare',
        sort_order: 1,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000002-2222-2222-2222-222222222222',
        label: 'SolidWorks & Altium Student Licenses',
        url: 'https://fhs-engineering.org/software-licenses',
        description: 'Access student CAD and EDA license keys provided by the engineering department sponsorship.',
        tier: 'primary',
        icon: 'Key',
        sort_order: 2,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000003-3333-3333-3333-333333333333',
        label: 'Makerspace Safety Waiver & Certifications',
        url: 'https://safety.fhs-engineering.org/makerspace-waiver',
        description: 'Mandatory safety protocol and certification status tracker required before using heavy machinery.',
        tier: 'primary',
        icon: 'ShieldAlert',
        sort_order: 3,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000004-4444-4444-4444-444444444444',
        label: 'Club GitHub Organization',
        url: 'https://github.com/fhs-engineering',
        description: 'Shared repositories for firmware, ROS2 packages, telemetry dashboards, and hardware designs.',
        tier: 'primary',
        icon: 'Github',
        sort_order: 4,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000005-5555-5555-5555-555555555555',
        label: '3D Print Queue & Material Requests',
        url: 'https://3dprint.fhs-engineering.org/queue',
        description: 'Submit STL files for Markforged Onyx and Bambu Lab X1-Carbon printers.',
        tier: 'secondary',
        icon: 'Printer',
        sort_order: 5,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000006-6666-6666-6666-666666666666',
        label: 'DigiKey Club Account Discount Portal',
        url: 'https://digikey.com/edu/discount',
        description: '15% educational discount for club purchases.',
        tier: 'secondary',
        icon: 'ShoppingBag',
        sort_order: 6,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000007-7777-7777-7777-777777777777',
        label: 'Machine Shop Reservation Calendar',
        url: 'https://calendar.google.com/calendar/u/0?cid=shop_calendar',
        description: 'Book time on the Tormach CNC mill or manual lathe.',
        tier: 'secondary',
        icon: 'Calendar',
        sort_order: 7,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000008-8888-8888-8888-888888888888',
        label: 'Club Constitution & Bylaws 2026-27',
        url: 'https://fhs-engineering.org/constitution.pdf',
        description: 'Official operational guidelines and election protocols.',
        tier: 'resource',
        icon: 'FileText',
        sort_order: 8,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
      {
        id: '80000009-9999-9999-9999-999999999999',
        label: 'FHS Engineering Travel & Reimbursement Policy',
        url: 'https://finance.fhs-engineering.org/travel-rules',
        description: 'Standard reimbursement limits for competition lodging and gas.',
        tier: 'resource',
        icon: 'Compass',
        sort_order: 9,
        is_active: true,
        updated_by: null,
        updated_at: new Date().toISOString(),
      },
    ],
    notifications: [],
    audit_log: [],
  };
}

// The store must live on globalThis: Next.js bundles this module separately per
// route, so a module-level variable would give every page its own isolated copy
// (breaking sessions and any cross-route state). globalThis is shared per process.
const GLOBAL_STORE_KEY = '__fhs_engineering_app_state__';

function readGlobalStore(): AppState | null {
  return ((globalThis as any)[GLOBAL_STORE_KEY] as AppState | undefined) ?? null;
}

function writeGlobalStore(store: AppState) {
  (globalThis as any)[GLOBAL_STORE_KEY] = store;
}

export function getDb(): AppState {
  let store = readGlobalStore();
  if (!store) {
    store = getInitialMockData();
    writeGlobalStore(store);
  }
  return store;
}

export function resetDb() {
  const store = getInitialMockData();
  writeGlobalStore(store);
  return store;
}
